### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by harsh-agarwal** [farismismar/Q-Learning-Power-Control#1]
Hi,

I am a beginner in the research field of DL and Communication and was looking forward towards your implementation of the paper "Deep Reinforcement Learning for Improving
Downlink mmWave Communication Performance" which mentions the link to this repository. Would be glad if you could give me a tentative timeline for the code that you would be putting in. 

Cheers
Harsh

**Comment by farismismar** [comment]
The paper was published recently under a slightly different name: https://github.com/farismismar/Deep-Reinforcement-Learning-for-5G-Networks
